[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

# Velocidad de comunicación y subida
monitor_speed = 115200
upload_speed = 921600 

# Configuración de compilación
upload_resetmethod = nodemcu
board_build.flash_mode = qio
board_build.partitions = huge_app.csv

# Flags de compilación mejorados
build_flags = 
    -I include
    -D CORE_DEBUG_LEVEL=0
    -D CONFIG_ARDUINO_LOOP_STACK_SIZE=16384 ; Aumenta el stack para procesos pesados como el Sniffer

# Dependencias de Librerías
lib_deps =
    nrf24/RF24 @ ^1.4.7
    olikraus/U8g2 @ ^2.35.9
    marian-craciunescu/ESP32Ping @ ^1.7
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    t-vk/ESP32 BLE Keyboard @ ^0.3.2
